# Generated by Django 4.0.2 on 2022-03-06 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_name', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
                ('roll', models.CharField(max_length=100)),
                ('req', models.CharField(max_length=400)),
                ('ctc', models.CharField(max_length=20)),
                ('passouts', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('roll', models.CharField(default='student', max_length=10)),
                ('verified', models.BooleanField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('PRN', models.CharField(max_length=100)),
                ('ug', models.CharField(max_length=100)),
                ('ug_marks', models.CharField(max_length=5)),
                ('ug_backlogs', models.CharField(max_length=5)),
                ('ug_stream', models.CharField(max_length=50)),
                ('ug_passout', models.CharField(max_length=5)),
                ('diploma', models.CharField(max_length=100, null=True)),
                ('diploma_marks', models.CharField(max_length=5, null=True)),
                ('diploma_stream', models.CharField(max_length=50)),
                ('hsc', models.CharField(max_length=100, null=True)),
                ('hsc_marks', models.CharField(max_length=100, null=True)),
                ('diploma_passout', models.CharField(max_length=5)),
                ('school', models.CharField(max_length=100)),
                ('school_marks', models.CharField(max_length=5)),
                ('school_passout', models.CharField(max_length=5)),
                ('extra_curriculam', models.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(default='pm', max_length=10)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
