# Generated by Django 4.0.5 on 2022-06-16 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('verified', models.BooleanField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('PRN', models.CharField(max_length=100)),
                ('extra_curriculam', models.CharField(max_length=400, null=True)),
                ('profile', models.FileField(default='avtar.png', null=True, upload_to=student.models.path_and_rename)),
                ('resume', models.FileField(null=True, upload_to=student.models.path_and_rename)),
                ('PlacementStatus', models.BooleanField(null=True)),
                ('Department', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ug_stream', models.CharField(max_length=100)),
                ('ug_admission', models.IntegerField(null=True)),
                ('ug_passout', models.IntegerField()),
                ('gap', models.BooleanField(default=False)),
                ('ug_backlog', models.PositiveIntegerField(default=0)),
                ('ug_fy_sem1', models.FloatField(null=True)),
                ('ug_sy_sem1', models.FloatField(null=True)),
                ('ug_ty_sem1', models.FloatField(null=True)),
                ('ug_be_sem1', models.FloatField(null=True)),
                ('ug_fy_sem2', models.FloatField(null=True)),
                ('ug_sy_sem2', models.FloatField(null=True)),
                ('ug_ty_sem2', models.FloatField(null=True)),
                ('ug_be_sem2', models.FloatField(null=True)),
                ('ug_total', models.FloatField(null=True)),
                ('ug_fy_atkt', models.IntegerField(null=True)),
                ('ug_sy_atkt', models.IntegerField(null=True)),
                ('ug_ty_atkt', models.IntegerField(null=True)),
                ('ug_be_atkt', models.IntegerField(null=True)),
                ('ug_fy_gap', models.IntegerField(null=True)),
                ('ug_sy_gap', models.IntegerField(null=True)),
                ('ug_ty_gap', models.IntegerField(null=True)),
                ('ug_be_gap', models.IntegerField(null=True)),
                ('diploma_college_name', models.CharField(max_length=100, null=True)),
                ('diploma_stream', models.CharField(max_length=50, null=True)),
                ('diploma_passout', models.IntegerField(null=True)),
                ('diploma_fy', models.FloatField(null=True)),
                ('diploma_sy', models.FloatField(null=True)),
                ('diploma_ty', models.FloatField(null=True)),
                ('diploma_total', models.FloatField(default=0, null=True)),
                ('hsc_college_name', models.CharField(max_length=100, null=True)),
                ('hsc_marks', models.FloatField(default=0, null=True)),
                ('hsc_passout', models.IntegerField(null=True)),
                ('school_name', models.CharField(max_length=100)),
                ('school_marks', models.FloatField(default=0)),
                ('school_passout', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Placementinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=50)),
                ('JoinDate', models.DateField()),
                ('CTC', models.IntegerField()),
                ('Offerletter', models.FileField(null=True, upload_to=student.models.offerletterUpload)),
                ('HRname', models.CharField(max_length=100)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Cocurriclar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
