# Generated by Django 4.0.3 on 2022-03-26 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('verified', models.BooleanField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('PRN', models.CharField(max_length=100)),
                ('extra_curriculam', models.JSONField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ug_stream', models.CharField(max_length=100)),
                ('ug_admmision', models.IntegerField(null=True)),
                ('ug_passout', models.IntegerField()),
                ('ug_fy_sem1', models.IntegerField(null=True)),
                ('ug_sy_sem1', models.IntegerField(null=True)),
                ('ug_ty_sem1', models.IntegerField(null=True)),
                ('ug_be_sem1', models.IntegerField(null=True)),
                ('ug_fy_sem2', models.IntegerField(null=True)),
                ('ug_sy_sem2', models.IntegerField(null=True)),
                ('ug_ty_sem2', models.IntegerField(null=True)),
                ('ug_be_sem2', models.IntegerField(null=True)),
                ('ug_fy_atkt', models.IntegerField(null=True)),
                ('ug_sy_atkt', models.IntegerField(null=True)),
                ('ug_ty_atkt', models.IntegerField(null=True)),
                ('ug_be_atkt', models.IntegerField(null=True)),
                ('ug_fy_gap', models.IntegerField(null=True)),
                ('ug_sy_gap', models.IntegerField(null=True)),
                ('ug_ty_gap', models.IntegerField(null=True)),
                ('ug_be_gap', models.IntegerField(null=True)),
                ('diploma_college_name', models.CharField(max_length=100, null=True)),
                ('diploma_stream', models.CharField(max_length=50, null=True)),
                ('diploma_passout', models.IntegerField(null=True)),
                ('diploma_fy', models.IntegerField(null=True)),
                ('diploma_sy', models.IntegerField(null=True)),
                ('diploma_ty', models.IntegerField(null=True)),
                ('diploma_total', models.IntegerField(null=True)),
                ('hsc_college_name', models.CharField(max_length=100, null=True)),
                ('hsc_marks', models.IntegerField(null=True)),
                ('hsc_passout', models.IntegerField(null=True)),
                ('school_name', models.CharField(max_length=100)),
                ('school_marks', models.IntegerField()),
                ('school_passout', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
