# Generated by Django 4.0.3 on 2022-03-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenteducation',
            old_name='ug_admmision',
            new_name='ug_admission',
        ),
    ]
