# Generated by Django 4.0.2 on 2022-03-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pm',
            name='roll',
        ),
    ]
