# Generated by Django 4.0.3 on 2022-03-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_ug_admmision_studenteducation_ug_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducation',
            name='diploma_fy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='diploma_sy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='diploma_ty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='hsc_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='school_marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_be_sem1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_be_sem2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_fy_sem1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_fy_sem2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_sy_sem1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_sy_sem2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_ty_sem1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_ty_sem2',
            field=models.FloatField(null=True),
        ),
    ]
