# Generated by Django 4.0.2 on 2022-03-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_pm_roll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='PM',
        ),
    ]
