# Generated by Django 4.0.3 on 2022-03-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studenteducation_diploma_fy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducation',
            name='diploma_total',
            field=models.FloatField(null=True),
        ),
    ]
