# Generated by Django 4.0.2 on 2022-03-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_diploma_remove_student_diploma_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducation',
            name='diploma_college_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='diploma_passout',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='diploma_stream',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='diploma_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='hsc_college_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='hsc_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='hsc_passout',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studenteducation',
            name='ug_admmision',
            field=models.IntegerField(null=True),
        ),
    ]
