# Generated by Django 4.0.3 on 2022-03-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studenteducation_diploma_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placementinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=50)),
                ('JoinDate', models.DateField()),
                ('CTC', models.IntegerField()),
                ('Offerletter', models.FileField(upload_to='')),
                ('HRname', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
