# Generated by Django 4.0.2 on 2022-03-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_event_pm_delete_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='roll',
            new_name='role',
        ),
        migrations.AddField(
            model_name='event',
            name='stu_applied',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
